### Thinking1 高德地图中的路径规划原理是怎样的？

+ 路径规划  
  + Dijkstra  
    + s：起点；S：已知到起点最短路径的点；U：未知到起点最短路径的点  
    + Step 1：S中只有起点s，从U中找出路径最短的  
    + Step 2：更新U中的顶点和顶点对应的路径  
    + 重复Step 1，Step 2
+ 地图导航原理  
 + 在路口设置节点
 + 节点间权重为流速  
 + 通过雷达获取流速（车密度） 
 + 发现新路径，是否切换路径？  
 + 动态计算，推荐 
 + 网络固定，流速变化
+ 路网节点多，复杂情况下如何进行实时响应  
 + 如从北京到上海
 + 分层计算
 + 先以城市为节点  
 + 城市之间再用动态规划（Dijkstra）计算

### Thinking2 football.gml数据集中，美国大学生足球联赛，包括115支球队，被分为12个联盟。为什么使用LPA标签传播进行社区发现，只发现了11个社区？

+ 核心在于：数据使用不一样——12个联盟是属于它的静态属性，不是比赛属性，而十一个社区是基于它的比赛成绩、比赛行为来去做的分析（动态分析）

### Thinking3 微博采用了类似FaceBook的EdgeRank算法，如果你给微博的信息流做设计，你会如何设计？

+ 广告推送，需粉丝亲密度、 内容质量 、原创程度等因素；
   + 粉丝粘度不高，发的东西，不一定出现在他（她）页面上；
   + 内容质量不高、原创程度不高，不一定会点击，被推送

## Action1 使用Python模拟下面的PageRank计算过程，求每个节点的影响力（迭代100次）

In [1]:
import numpy as np

In [2]:
a = np.array([[0, 1/2, 1, 0], 
           [1/3, 0, 0, 1/2],
           [1/3, 0, 0, 1/2],
           [1/3, 1/2, 0, 0]])
b = np.array([1/4, 1/4, 1/4, 1/4])

w = b
for i in range(100):
    w = np.dot(a, w)
    print(w)

[0.375      0.20833333 0.20833333 0.20833333]
[0.3125     0.22916667 0.22916667 0.22916667]
[0.34375 0.21875 0.21875 0.21875]
[0.328125   0.22395833 0.22395833 0.22395833]
[0.3359375  0.22135417 0.22135417 0.22135417]
[0.33203125 0.22265625 0.22265625 0.22265625]
[0.33398438 0.22200521 0.22200521 0.22200521]
[0.33300781 0.22233073 0.22233073 0.22233073]
[0.33349609 0.22216797 0.22216797 0.22216797]
[0.33325195 0.22224935 0.22224935 0.22224935]
[0.33337402 0.22220866 0.22220866 0.22220866]
[0.33331299 0.222229   0.222229   0.222229  ]
[0.33334351 0.22221883 0.22221883 0.22221883]
[0.33332825 0.22222392 0.22222392 0.22222392]
[0.33333588 0.22222137 0.22222137 0.22222137]
[0.33333206 0.22222265 0.22222265 0.22222265]
[0.33333397 0.22222201 0.22222201 0.22222201]
[0.33333302 0.22222233 0.22222233 0.22222233]
[0.33333349 0.22222217 0.22222217 0.22222217]
[0.33333325 0.22222225 0.22222225 0.22222225]
[0.33333337 0.22222221 0.22222221 0.22222221]
[0.33333331 0.22222223 0.22222223 0.22222223]


## Action2 使用TextRank对新闻进行关键词提取，及文章摘要输出

In [4]:
from textrank4zh import TextRank4Keyword, TextRank4Sentence
import jieba

 #### TextRank4Keyword.analyse 参数 
+ :param text: 文本内容
+ :param window: 窗口大小，整型，用于构造单词之间的边，去默认值为2
+ :param lower: 是否将英文文本转换为小写，默认值为False
+ :param vertex_source: 选择使用words_no_filter, words_no_stop_words, words_all_filters中的哪一个来构造pagerank对应的图中的节点。默认值为`'all_filters'`，可选值为`'no_filter', 'no_stop_words', 'all_filters'`。关键词也来自`vertex_source`
+ :param edge_source:选择使用words_no_filter, words_no_stop_words, words_all_filters中的哪一个来构造pagerank对应的图中的节点之间的边。默认值为`'no_stop_words'`，可选值为`'no_filter', 'no_stop_words', 'all_filters'`。边的构造要结合`window`参数。
+ :param pagerank_config:pagerank算法参数配置，阻尼系数为0.85

#### get_keywords 参数
+ :param num: 返回的关键词个数
+ :param word_min_len: 最小关键词长度


In [5]:
text = '一个超过5000万人关注的大项目，您参加了吗?央视新闻新媒体推出武汉火神山、雷神山医院建设现场24小时不间断直播，短短几天时间吸引无数关心医院建设的网友围观。其中最受广大网友关注的火神山两路镜头对准的正是中建三局三公司承建区域，截至30日13:50，在看人数已突破5000万。热心的网友们自称为“云监工”或“网络包工头”，自发在评论区实行“两班倒”打卡“监督”还热切、尽职的互动交流起了“工作”。这一称号数度登上微博热搜。繁忙却相对单调枯燥的施工画面，因为“云监工”们脑洞大开的评论而妙趣横生，他们给所有的机器都起好了名字，根据颜色亲昵的叫上了小红、小黄、小蓝，没事就来视频里蹲自己喜欢的机器出现还编起了段子，绘起了同人。不仅现场的各种机械设备有了“粉丝团”，有细心者甚至数出了直播画面中中建三局三公司这一施工区域中出镜的管理人员与工友人数。记者了解到，火神山医院建设方之一的中建三局三公司在四川也有不少项目，德阳市妇女儿童专科医院项目也是该公司在建设。最后，让我们一起以比直播镜头更近、更鲜活的视角来重温让万千网友为之惊叹鼓舞的奋斗时刻!'

# 输出关键词，设置文本小写，窗口为2
tr4w = TextRank4Keyword()
tr4w.analyze(text=text, lower=True, window=3)
print('关键词：')
for item in tr4w.get_keywords(20, word_min_len=2):
    print(item.word, item.weight)

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\Administrator\AppData\Local\Temp\jieba.cache
Loading model cost 0.786 seconds.
Prefix dict has been built successfully.


关键词：
网友 0.029170901041798297
建设 0.023700544450781045
项目 0.02087288098364101
火神 0.02046655848070826
医院 0.01926349561018545
公司 0.018692959173468575
直播 0.017398810931183124
人数 0.01620157574010347
机器 0.01618046989870025
评论 0.01610944971816664
交流 0.015020901537043706
画面 0.014087299546756799
监工 0.014080614493744658
关注 0.014002791567125606
区域 0.013480406774218308
颜色 0.012744156598282055
现场 0.012216928076756598
施工 0.01215042022000445
中建 0.011984519756586157
鼓舞 0.011489904483475361


#### get_key_sentences 参数
+ text                 --  文本内容，字符串。
+ lower                --  是否将文本转换为小写。默认为False。
+ source               --  选择使用words_no_filter, words_no_stop_words, words_all_filters中的哪一个来生成句子之间的相似度。
								 默认值为`'all_filters'`，可选值为`'no_filter', 'no_stop_words', 'all_filters'`。
+ sim_func             --  指定计算句子相似度的函数。

#### get_key_sentences
+ 获取最重要的num个长度大于等于sentence_min_len的句子用来生成摘要

In [6]:
# 输出重要的句子
tr4s = TextRank4Sentence()
tr4s.analyze(text=text, lower=True, source = 'all_filters')
print('摘要：')
# 重要性较高的三个句子
for item in tr4s.get_key_sentences(num=3):
    # index是语句在文本中位置，weight表示权重
    print(item.index, item.weight, item.sentence)

摘要：
2 0.14109928864004823 其中最受广大网友关注的火神山两路镜头对准的正是中建三局三公司承建区域，截至30日13:50，在看人数已突破5000万
1 0.12613737472845335 央视新闻新媒体推出武汉火神山、雷神山医院建设现场24小时不间断直播，短短几天时间吸引无数关心医院建设的网友围观
6 0.11985679806834681 不仅现场的各种机械设备有了“粉丝团”，有细心者甚至数出了直播画面中中建三局三公司这一施工区域中出镜的管理人员与工友人数
